'From Cuis 6.0 [latest update: #5608] on 8 February 2023 at 7:26:23 pm'!
'Description '!
!provides: 'SmallMud' 1 1!
SystemOrganization addCategory: 'SmallMud-Core'!
SystemOrganization addCategory: 'SmallMud'!


!classDefinition: #SmallMudConnection category: 'SmallMud-Core'!
Object subclass: #SmallMudConnection
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SmallMud-Core'!
!classDefinition: 'SmallMudConnection class' category: 'SmallMud-Core'!
SmallMudConnection class
	instanceVariableNames: ''!

!classDefinition: #SmallMudServer category: 'SmallMud-Core'!
Object subclass: #SmallMudServer
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SmallMud-Core'!
!classDefinition: 'SmallMudServer class' category: 'SmallMud-Core'!
SmallMudServer class
	instanceVariableNames: ''!

!classDefinition: #SmallMudSocketListener category: 'SmallMud-Core'!
Object subclass: #SmallMudSocketListener
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SmallMud-Core'!
!classDefinition: 'SmallMudSocketListener class' category: 'SmallMud-Core'!
SmallMudSocketListener class
	instanceVariableNames: ''!

